const express = require('express');
const router = express.Router();
const { getProcessedHeroCarousel, getMovieById, getStreamUrl, getSectionsWithMovies, getCategoriesByType, getSectionswithLiveTv, getAllLiveTvS, getLiveStreamUrl } = require('../controller/public.controller');
router.get('/hero-carousel', getProcessedHeroCarousel);
router.get('/movies/:id', getMovieById);
router.get('/stream-url/:providerId/:streamId', getStreamUrl);
router.get('/sections', getSectionsWithMovies);
router.get('/sections/live-tv', getSectionswithLiveTv);
router.get('/lives', getAllLiveTvS);
router.get('/livestreamurl/:providerId/:streamId', getLiveStreamUrl);
router.get('/categories/:content_type', getCategoriesByType);
module.exports = router;